### ISSUE TITLE
Numbers formating

### ISSUE THREAD

**Issue by bork1n** [makarski/probation-csv#33]
Currently the application outputs numbers in `eval` like `4.6666665`. This makes sheets look ugly.
We don't care about such a granularity here. If we can output just `4.7`(%.1f), this will improve overall impression from the sheet and eliminate the need for adjusting the numbers.

**Comment by makarski** [comment]
Resolved in https://github.com/makarski/esurvey/commit/321e6a18fe1d595caa52f531289261f55dfa8214
